#!/bin/sh
#Collect static files
python /home/dotcloud/current/django_project/manage.py collectstatic --settings settings_deployment --noinput

#Syncdb
python /home/dotcloud/current/django_project/manage.py syncdb --settings settings_deployment

#Run south to migrate database
python /home/dotcloud/current/django_project/manage.py migrate --settings settings_deployment
